### ISSUE TITLE
"Uncaught (in promise): Connection was not successfull" when calling connectToWifi.

### ISSUE THREAD

**Issue by shootdaj** [hypery2k/cordova-hotspot-plugin#86] opened 2017-12-25 04:32 UTC
OS: Windows 10
Cordova Version: 4.5.2 (the Ionic NPM Package version, which I assume is the same as the Cordova version)
Android Version: 8.1.0

Steps to recreate: Call hotspot.connectToWifi()

Pretty self-explanatory. I get the error:

Uncaught (in promise): Connection was not successfull

When I call hotspot.connectToWifi(). Not sure why.

I believe this issue is related to the issue you created: https://github.com/hypery2k/cordova-hotspot-plugin/issues/4

It says closed and only contributers can post on that issue so I had to create a new one.

**Comment by hypery2k** [comment] 2018-01-02 21:30
the plugin is discontinued, so I will not maintain this repo anymore

**Comment by hypery2k** [comment] 2018-01-02 21:31
duplicate of #81

**Closed as completed by hypery2k** 2018-01-02 21:31 UTC
